language: python
python:
    - "3.6.7"

# Install dependencies
install:
    - pip3 install -r requirements.txt
    - pip3 install coveralls
# Run tests
script:
    - pytest --cov=app
    - coverage run --source=app.api.v1 -m pytest && coverage report
after_success:
    - coveralls
