language: python
python:
    - "3.6.7"

# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install coveralls
# Run tests
script:
    - pytest
    - coverage run --source=app.api.v1 -m pytest && coverage report
    
after_success:
    - coveralls
