language: python
python:
    - "3.6.7"

# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
# Run tests
script:
    -python -m pytest tests/

after_success:
    - coveralls
